// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: SocketProtocol.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace SocketProtocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MainPack : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public RequestCode requestCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ActionCode actionCode { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ReturnCode returnCode { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public RegisterPack registerPack { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public LoginPack loginPack { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"roomPack")]
        public global::System.Collections.Generic.List<RoomPack> roomPacks { get; } = new global::System.Collections.Generic.List<RoomPack>();

        [global::ProtoBuf.ProtoMember(7, Name = @"playerPack")]
        public global::System.Collections.Generic.List<PlayerPack> playerPacks { get; } = new global::System.Collections.Generic.List<PlayerPack>();

        [global::ProtoBuf.ProtoMember(8, Name = @"str")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Str { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RegisterPack : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string DisplayName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Password { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginPack : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Password { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoomPack : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string RoomName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int MaxNum { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int CurrentNum { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public RoomState roomState { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"ID")]
        public int Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerPack : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string DisplayName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"UID")]
        public int Uid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum RequestCode
    {
        RequestNone = 0,
        User = 1,
        Room = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ActionCode
    {
        ActionNone = 0,
        Register = 1,
        Login = 2,
        CreateRoom = 3,
        FindRoom = 4,
        PlayerList = 5,
        JoinRoom = 6,
        Exit = 7,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ReturnCode
    {
        ReturnNone = 0,
        Succeed = 1,
        Failed = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum RoomState
    {
        OutOfGame = 0,
        InGame = 1,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
